[project]
name = "rpn-transformers"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ollama",
    "numpy",
    "tqdm",
    "matplotlib",
]
